### ISSUE TITLE
Propuesta de mejora de RRSS

### ISSUE THREAD

**Issue by David-Estevez** [asrob-uc3m/actas#141]
Es por todos conocido que la única red social que se encuentra al día es Twitter, gracias a @JorFru (ver #78). De hecho, el último mensaje de ASROBot decía:

> En última reunión hicísteis cosas muy chulas, deberíamos contárselo al mundo en las redes sociales! En Facebook no hay ningún post desde hace 3 meses. En Google + no hay ningún post desde hace 5 meses.

Ya que no conseguimos a nadie que publique en esas redes, propongo duplicar lo que se publique en Twitter, o bien de forma manual, o bien con algún método automático en Facebook y G+. ¿Qué os parece la idea?

Edit: 
- [x] Quitar G+ de la web https://github.com/asrob-uc3m/asrob-uc3m.github.io/issues/23 Gracias @jgvictores 
- [x] Quitar G+ de la Wiki https://github.com/asrob-uc3m/actas/issues/141#issuecomment-420270306 Gracias @jgvictores 
- [x] Publicar post de despedida enlazando a las redes sociales en uso Gracias @jorfru
- [x] Modificar el bot para que no notifique G+

**Comment by daavm** [comment]
A mi me gusta la idea, creo que se podría fácilmente hacer que el propio bot duplique los tweets en forma de publicaciones de Facebook y G+. Si nadie se presta a ello, no me importaría hacerlo :+1:

**Comment by jgvictores** [comment]
Twitter->Facebook, las mejores opciones hace años eran las que ellos mismos ofrecían (vs app terceros o bot nuestro). Las webs han cambiado, pero es posible que una de ellas sea: https://help.twitter.com/es/managing-your-account/link-twitter-to-facebook

Para twitter->g+ en una búsqueda rápida sólo encontré apps terceros que tb manejaría Facebook, pero de primeras diría de intentar con lo oficial siempre que se pueda.

Independientemente del mecanismo, lo importante es que se generen posts en condiciones. Querremos multimedia + texto. Lo digo pq algunas apps solo publican URL del post en el otro sitio, que no es bonito, ni se percibe la info de forma inmediata.

**Comment by Siotma** [comment]
Claramente, este sistema aumentaría nuestra presencia en G+ y Facebook sin aumentar el trabajo del responsable de redes. Además, no quita que en algún momento se quiera publicar un post más largo.

Me parece muy adecuada la condición que propone @jgvictores : la apariencia de la publicación debe contener el mismo texto, imágenes y/o vídeos.

**Comment by jgvictores** [comment]
https://techcrunch.com/2018/08/01/psa-cross-posting-tweets-to-facebook-no-longer-works-as-of-today/ : (

**Comment by David-Estevez** [comment]
Reunión 10/09/2018: poner post de despedida en G+ (redirigiendo a Twitter, Fb y web) y hacer que el bot deje de notificar G+.

**Comment by JorFru** [comment]
- [ ] Quitar G+ de la web https://github.com/asrob-uc3m/asrob-uc3m.github.io/issues/23
- [ ] Publicar post de despedida enlazando a las redes sociales en uso

**Comment by JorFru** [comment]
He terminado la tarea que me correspondía como responsable de RRSS.
Sin embargo no me veo capaz de tocar la web sin romper cosas. Se lo dejo a otro.
https://plus.google.com/u/3/117320353227938266035/posts/9abMZkm2Qpn
TERMINADO
![captura de pantalla_2018-09-11_14-33-59](https://user-images.githubusercontent.com/11017088/45360416-d5863400-b5cf-11e8-98c0-c8b3566c8821.png)

**Comment by jgvictores** [comment]
Ampilé https://github.com/asrob-uc3m/actas/issues/141#issuecomment-420263526 a la wiki, donde lo quité en http://asrob.uc3m.es/index.php?title=Main_Page&type=revision&diff=12934&oldid=12910

**Comment by JorFru** [comment]
Te asigno para tu ración de asrobpoints

**Comment by David-Estevez** [comment]
Editado el mensaje con atribuciones correctas ("Al César lo que es el del César [...]")

**Comment by jgvictores** [comment]
> @dmarcosm estaba jugando con APIs para poder hacerlo mediante ASROBot, igual él nos puede dar más detalles de cómo ve el asunto...

Entiendo que la ruptura con Twitter justo fue por APIs, rumores de que es consecuencia de todo lo de protección de datos. @dmarcosm tal vez un poco de [Selenium WebDriver](https://www.seleniumhq.org/projects/webdriver/) ayude para el _hack_, aunque quizás no sea lo más elegante.

**Comment by jgvictores** [comment]
Related con esta issue en general, documentar las vías de comunicación en la web, abrí https://github.com/asrob-uc3m/asrob-uc3m.github.io/issues/26

**Comment by David-Estevez** [comment]
La notificación de G+ ya está desactivada.

Por otro lado, como sólo queda por solucionar lo de Fb, y tratando de conseguir issues más atómicas que sean más fáciles de cerrar, voy a mover el desarrollo de esa feature a #159. Por tanto, doy por cerrada esta issue.
