### ISSUE TITLE
Runión de asrob

### ISSUE THREAD

**Issue by madelgj** [asrob-uc3m/actas#157]
Necesitamos convocar una nueva reunión para toda la asociación para resolver los siguientes temas:

- Traspaso de poderes oficialmente

- Organización de la semana de asociaciones

**Comment by JorFru** [comment]
Creo que quizás encaja con lo que @madelgj sugiere, he encontrado lo siguiente en [estatutos](https://asrob-uc3m.gitbooks.io/estatutos/content/puestos_de_responsabilidad.html)
> Los representantes de cada grupo se consideran vocales de la Junta Directiva, y deberán estar presentes en las reuniones internas como representación de sus compañeros de grupo de trabajo.

Creo que son deberes pendientes, porque hace más de un año que esto no se revisa / reelige.

**Comment by JorFru** [comment]
He comprado pegatinas, que ayudarán mucho a categorizar qué hay en cada
caja.

**Comment by JorFru** [comment]
https://doodle.com/poll/dxk76dxmhxvwt2wa
Voten!

**Comment by CeciliaVa** [comment]
Esta reunión se ha propuesto atendiendo a las necesidades de la Asociación y los miembros activos, en ella se tratarán los siguientes temas:

- [ ] Fijar los pasos a seguir concretos para lograr una efectiva organización de armarios atendiendo a las propuestas de esta misma issue y las issues #137 #93 #37 y #1.

- [ ] Tratar y organizar todo lo relativo a las Semana de asociaciones 2018, considerando lo ya mencionado en las issues #131 y #150.

- [ ] Buscar soluciones y mejoras organizativas para las respuestas de emails y redes sociales teniendo en cuenta las sugerencias de las issues #141 #158 #159 #53 y de las issues #19 y #17 de estatutos.

- [ ] En relación con el punto anterior y con lo sugerido en esta misma issue, revisar la Junta Directiva y puestos de responsabilidad. En especial estudiar la necesidad del responsable de emails y sus consiguientes responsabilidades según lo decidido en el punto anterior.

- [ ] Rescatar la issue #18 de estatutos que recobra importancia con la sucesión de cargos y puestos de responsabilidad.

Debido a la importancia y urgencia de algunos asuntos sugiero que para no embrollarnos en trámites burocráticos se realicen votaciones vinculantes durante la reunión como se hicieron en la pasada, si todos los miembros activos de la asociación están de acuerdo.

**Comment by CeciliaVa** [comment]
Esta reunión se ha propuesto atendiendo a las necesidades y peticiones de la Asociación y sus miembros activos. En la reunión se tratarán los siguientes temas:

- [ ] Fijar los pasos a seguir concretos para lograr una organización efectiva de los armarios, debe tenerse en cuenta lo ya mencionado en esta misma issue y en las issues #137 #93 #37 y #1.

- [ ] Aclarar y organizar todo lo relativo a la Semana de asociaciones 2018 y sus actividades atendiendo a las issues #131 y #150.

- [ ] Considerando la participación de la Asociación en la Bilbao Maker Faire, elegir a un representante para ir, valorando las disponibilidad y el ofrecimiento de los compañeros, reflejados en la issue #160.

- [ ] Revisar y mejorar organizativamente los medios de respuestas en redes sociales y a emails, considerando la automatización de respuestas y demás sugerencias expuestas en las issues #141 #159 #158 #53 y en las issues 19 y 17 de los estatutos.

- [ ] En relación con el punto anterior revisar la necesidad del puesto de responsable de emails según lo debatido anteriormente y actualizar las tareas asociadas a ese cargo.

- [ ] Según lo descrito en esta misma issue, reelegir todos los cargos de la Junta Directiva y puestos de responsabilidad que no se votaron en la última reunión, especialmente el puesto de responsable de impresoras 3D de acuerdo con la issue #154.

- [ ] Rescatar la issue 18 de estatutos que recobra importancia con la sucesión de cargos y puestos de responsabilidad.

Debido a la importancia y urgencia de algunos asuntos sugiero que para no embrollarnos en trámites burocráticos se realicen votaciones vinculantes durante la reunión, como se hicieron en la pasada, si todos los miembros activos de la asociación están de acuerdo.

**Comment by jgvictores** [comment]
Un par de cosas que se me habían escapado:
1. Mejoramos algo la wiki para dar más visibilidad a la web: [cambios](http://asrob.uc3m.es/index.php?title=Main_Page&type=revision&diff=12941&oldid=12937)
1. Se habló de https://github.com/asrob-uc3m/asrob-uc3m.github.io/issues/26 y se votó a favor

Cuando pueda, paso los comentarios de esta issue a fichero de este repo, actualizo `SUMMARY.md`, y cierro issue.
